### ISSUE TITLE
RsunX, RsunY and RsunZ data

### ISSUE THREAD

**Issue by sgangoly** [mburhanpurkar/asteroid#1]
Hi, 
Great code! I am NOT an SSPer and came across your program.

Just wondering about the source of your Rsun data for Magellan coded into the program. Is this data taken from NASA JPL or were they "measured" somehow? If measured how please?

Appreciate the guidance :-)

Thanks 

santanu

**Comment by mburhanpurkar** [comment]
Hi Santanu,

Yep, all the data comes from either my own observations or NASA JPL. In
this case, Rsun comes from JPL. It is possible to calculate this yourself
by simulating the solar system, if you like. I tried doing this for fun,
but the simulation becomes inaccurate without copious corrections.

-Maya

**Comment by sgangoly** [comment]
Hi Maya,

Many thanks for that indeed! I treid to look up the Rsun data at JPL Horizon but do not seem to find matching data for the equivalent JD date of yours for Magellan ( 11 July 2015 06:34:31.9 ?)

However, it is entirely possible that I am looking at the wrong data on JPL :-)

Thanks and best regards
Santanu

**Comment by sgangoly** [comment]
Hi Maya,

Firstly, many thanks for all your guidance with Rsun. Really appreciate that I know you must be very busy and please don't bother responding if I am taking up too much of your time with stupid questions! I am a full time IT slave and am dabbling with asteroid orbits as a hobby in recent times. Since its a hobby, its eating up way more of my time than anything else ! :-)

My sincere apologies for bugging you again, but thought perhaps with your experience and knowhow, you would be able to point me easily to where I am messing up.

I tried out some data with on your code. I am ashamed to admit that I am getting ridiculous values for eccentricity and of course the calculation crashes. I took the Rsun data from NASA JPL Horizon site.

Piece of actual code for data:

# Actual Data
ra1 = 20.15818889 * 15 * pi / 180  # Converted to radians
dec1 = 5.27211111 * pi / 180  # CTR
t1 = 2458302.552801  # UTC
R1 = [-1.912044656990578e-1, 9.985240288089093e-1, -4.338365857342309e-5]    # AU
ra2 = 20.12270278 * 15 * pi / 180   # CTR
dec2 = 4.89527778 * pi / 180  # CTR
t2 = 2458305.581204  # UTC
R2 = [-2.412588907956069e-1, 9.876553804178101e-1, -4.396113657919444e-5]    # AU
ra3 = 20.06899444 * 15 * pi / 180   # CTR
dec3 = 4.29469444 * pi / 180  # CTR
t3 = 2458309.589792  # UTC
R3 = [-3.065557690751595e-1, 9.693469584920573e-1, -4.267111067443691e-5]    # AU

#########################
RA_DEC:

       RA                DEC                  JD                     UT
20 09 29.48     05 16 19.6    2458302.552801    2018 Jul 3	01:16:02.0
20 07 21.73     04 53 43.0    2458305.581204    2018 Jul 6	01:56:56.0
20 04 08.38     04 17 40.9    2458309.589792    2018 Jul 10	02:09:18.0


Rsun Values from NASA JPL:
2458302.552800926 = A.D. 2018-Jul-03 01:16:02.0000 TDB 
 X =-1.912044656990578E-01 Y = 9.985240288089093E-01 Z =-4.338365857342309E-05
 VX=-1.661476094284718E-02 VY=-3.165166858529901E-03 VZ=-3.455133844200253E-07
 LT= 5.871772069385453E-03 RG= 1.016665818100608E+00 RR= 1.605379079536676E-05


2458305.581203704 = A.D. 2018-Jul-06 01:56:56.0000 TDB 
 X =-2.412588907956069E-01 Y = 9.876553804178101E-01 Z =-4.396113657919444E-05
 VX=-1.643489063728032E-02 VY=-4.011577063699668E-03 VZ=-7.905334686476778E-10
 LT= 5.871941410285066E-03 RG= 1.016695138568469E+00 RR= 2.958423321158688E-06

2458309.589791667 = A.D. 2018-Jul-10 02:09:18.0000 TDB 
 X =-3.065557690751595E-01 Y = 9.693469584920573E-01 Z =-4.267111067443691E-05
 VX=-1.613077408889674E-02 VY=-5.120511993270912E-03 VZ= 6.533981684015872E-07
 LT= 5.871773721424504E-03 RG= 1.016666104142303E+00 RR=-1.826646703910530E-05

ONLY thing I have changed so far in your code is the above data and the data for the orbital elements from JPL.

I have concerted RA and DEC in decimal format and the UT dates into JD as per your code ( please see above if you have the time)

Any advice/guidance will be really appreciated. This is bugging me a bit :-). Many thanks for  your excellent work and amazing guidance.

Sincerely
Santanu

**Comment by sgangoly** [comment]
Hi Again,

I finally managed to write a code which "appears " to give near JPL values :-) . So I am closing this one.

Thanks a lot!
Best Regards
Santanu
